// Dynamic Recommendation Engine
const recommendationDatabase = {
  Happy: {
    movies: [
      { title: "The Grand Budapest Hotel", reason: "Colorful and whimsical storytelling" },
      { title: "Knives Out", reason: "Fun mystery with great chemistry" },
      { title: "Paddington 2", reason: "Heartwarming and delightful" },
      { title: "Spirited Away", reason: "Magical adventure that lifts your spirits" },
      { title: "Good as Hell", reason: "Uplifting and celebratory" },
      { title: "La La Land", reason: "Dreams and music in perfect harmony" },
      { title: "The Lego Movie", reason: "Pure joy and creativity" },
      { title: "Clueless", reason: "Fun, colorful, and feel-good" },
    ],
    music: [
      { title: "Walking on Sunshine - Katrina & The Waves", reason: "Pure positivity" },
      { title: "Good as Hell - Lizzo", reason: "Self-love anthem" },
      { title: "Don't Stop Me Now - Queen", reason: "Energetic and triumphant" },
      { title: "Walking in Sunshine - M People", reason: "Uplifting vibes" },
      { title: "Here Comes the Sun - The Beatles", reason: "Timeless happiness" },
      { title: "Levitating - Dua Lipa", reason: "Feels like flying" },
      { title: "Shut Up and Dance - WALK THE MOON", reason: "Fun and carefree" },
      { title: "Blinding Lights - The Weeknd", reason: "Energetic and catchy" },
    ],
    books: [
      { title: "The House in the Cerulean Sea - TJ Klune", reason: "Heartwarming found family" },
      { title: "Red, White & Royal Blue - Casey McQuiston", reason: "Fun romance with humor" },
      { title: "Disco Inferno - Nicky Stivers", reason: "Feel-good adventure" },
      { title: "A Man Called Ove - Fredrik Backman", reason: "Grumpy but heartfelt" },
      { title: "Eleanor Oliphant Is Completely Fine", reason: "Uplifting transformation" },
      { title: "The Midnight Library - Matt Haig", reason: "Hopeful and magical" },
      { title: "Circe - Madeline Miller", reason: "Empowering and enchanting" },
    ],
    activities: [
      { title: "Dance like nobody's watching", reason: "Express your joy" },
      { title: "Call a friend and laugh together", reason: "Share the happiness" },
      { title: "Watch funny stand-up comedy", reason: "Amplify the laughter" },
      { title: "Do something you love", reason: "Lean into the joy" },
      { title: "Create art or music", reason: "Channel happiness creatively" },
      { title: "Go for a scenic walk", reason: "Enjoy the moment" },
      { title: "Cook your favorite meal", reason: "Celebrate with food" },
      { title: "Play games with friends", reason: "Keep the fun going" },
    ],
  },

  Sad: {
    movies: [
      { title: "Life is Beautiful", reason: "Hopeful despite heartbreak" },
      { title: "About Time", reason: "Touching and reflective" },
      { title: "The Shawshank Redemption", reason: "Redemption and hope" },
      { title: "Moonlight", reason: "Tender and poetic" },
      { title: "Garden State", reason: "Beautiful melancholy" },
      { title: "A Ghost Story", reason: "Contemplative and profound" },
      { title: "Blade Runner 2049", reason: "Moody and atmospheric" },
      { title: "Requiem for a Dream", reason: "Heavy but cathartic" },
    ],
    music: [
      { title: "The Night We Met - Lord Huron", reason: "Nostalgic and melancholic" },
      { title: "Skinny Love - Bon Iver", reason: "Vulnerable and raw" },
      { title: "Hurt - Johnny Cash", reason: "Deep and honest" },
      { title: "Creep - Radiohead", reason: "Sad but relatable" },
      { title: "Someone Like You - Adele", reason: "Emotional release" },
      { title: "Yesterday - The Beatles", reason: "Timeless sadness" },
      { title: "Mad World - Gary Jules", reason: "Introspective" },
      { title: "Black - Pearl Jam", reason: "Melancholic beauty" },
    ],
    books: [
      { title: "The Fault in Our Stars - John Green", reason: "Bittersweet beauty" },
      { title: "A Little Life - Hanya Yanagihara", reason: "Deep emotional journey" },
      { title: "Everything I Never Told You - Celeste Ng", reason: "Haunting and tender" },
      { title: "The Midnight Library - Matt Haig", reason: "Hopeful reflection" },
      { title: "Before the Coffee Gets Cold", reason: "Poignant and touching" },
      { title: "Crying in H Mart - Michelle Zauner", reason: "Cathartic grief memoir" },
      { title: "Ninth House - Leigh Bardugo", reason: "Darkly complex" },
    ],
    activities: [
      { title: "Write in a journal", reason: "Process your feelings" },
      { title: "Listen to sad songs", reason: "Validate the emotion" },
      { title: "Call someone you trust", reason: "Share the weight" },
      { title: "Take a long shower/bath", reason: "Let emotions flow" },
      { title: "Watch the sunset", reason: "Find quiet peace" },
      { title: "Write a letter (don't send)", reason: "Express what's inside" },
      { title: "Volunteer or help others", reason: "Find purpose" },
      { title: "Cry if you need to", reason: "Emotional release is healing" },
    ],
  },

  Anxious: {
    movies: [
      { title: "Mr. Rogers Documentary", reason: "Calming and comforting" },
      { title: "The Secret of Kells", reason: "Beautiful and reassuring" },
      { title: "Amélie", reason: "Whimsical and lighthearted" },
      { title: "Spirited Away", reason: "Escapist and magical" },
      { title: "Howl's Moving Castle", reason: "Cozy and enchanting" },
      { title: "Paddington", reason: "Gentle and heartwarming" },
      { title: "Studio Ghibli films", reason: "Soothing and beautiful" },
      { title: "Midnight in Paris", reason: "Dreamy and escapist" },
    ],
    music: [
      { title: "Calm Down - Rema", reason: "Soothing rhythm" },
      { title: "Weightless - Marconi Union", reason: "Scientifically calming" },
      { title: "Peaceful Piano Collection - Various", reason: "Instrumental relaxation" },
      { title: "Ocean Sounds with Music", reason: "Nature-inspired calm" },
      { title: "Ambient by Eno", reason: "Dissolving anxiety" },
      { title: "Forest Sounds Playlist", reason: "Nature therapy" },
      { title: "Meditation Music Collection", reason: "Grounding and centering" },
      { title: "Lo-fi Hip Hop", reason: "Non-intrusive background" },
    ],
    books: [
      { title: "The Courage to Be Disliked", reason: "Philosophical comfort" },
      { title: "Educated - Tara Westover", reason: "Inspiring resilience" },
      { title: "Braiding Sweetgrass - Robin Wall Kimmerer", reason: "Grounding and healing" },
      { title: "The Book of Awakening - Mark Nepo", reason: "Daily wisdom" },
      { title: "Atomic Habits - James Clear", reason: "Practical and empowering" },
      { title: "Daring Greatly - Brené Brown", reason: "Courage through vulnerability" },
      { title: "Light novel comfort reads", reason: "Easy and uplifting" },
    ],
    activities: [
      { title: "Practice deep breathing", reason: "Calm your nervous system" },
      { title: "Try meditation or yoga", reason: "Ground yourself" },
      { title: "Take a warm bath", reason: "Physical relaxation" },
      { title: "Go outside in nature", reason: "Fresh air resets anxiety" },
      { title: "Do progressive muscle relaxation", reason: "Release tension" },
      { title: "Journal your worries", reason: "Get them out of your head" },
      { title: "Make a to-do list", reason: "Control the chaos" },
      { title: "Spend time with pets", reason: "Unconditional comfort" },
    ],
  },

  Calm: {
    movies: [
      { title: "Lost in Translation", reason: "Serene and meditative" },
      { title: "My Neighbor Totoro", reason: "Peaceful countryside magic" },
      { title: "The Secret of Kells", reason: "Beautiful animation" },
      { title: "A Quiet Place (Part 1)", reason: "Meditative silence" },
      { title: "Zen and the Art of Motorcycle Maintenance", reason: "Philosophical peace" },
      { title: "Call Me By Your Name", reason: "Slow-burn intimate" },
      { title: "Before Sunrise", reason: "Quiet conversation" },
      { title: "Ikiru", reason: "Life-affirming and peaceful" },
    ],
    music: [
      { title: "Spiegel im Spiegel - Arvo Pärt", reason: "Minimalist perfection" },
      { title: "Gymnopédies - Erik Satie", reason: "Timeless tranquility" },
      { title: "Moon River - Various Artists", reason: "Gentle and timeless" },
      { title: "Nocturne No. 2 - Chopin", reason: "Peaceful classical" },
      { title: "Ambient 1 - Brian Eno", reason: "Sonic space to breathe" },
      { title: "Folkways - Iron & Wine", reason: "Intimate acoustic" },
      { title: "Nuvole Bianche - Ludovico Einaudi", reason: "Flowing piano" },
      { title: "Nick Drake Discography", reason: "Introspective folk" },
    ],
    books: [
      { title: "Norwegian Wood - Haruki Murakami", reason: "Meditative and introspective" },
      { title: "The Remains of the Day - Kazuo Ishiguro", reason: "Thoughtful prose" },
      { title: "Braiding Sweetgrass - Robin Wall Kimmerer", reason: "Peaceful wisdom" },
      { title: "The Old Man and the Sea - Hemingway", reason: "Timeless meditation" },
      { title: "Zen and the Art of Motorcycle Maintenance", reason: "Philosophical calm" },
      { title: "The Pilgrimage - Paulo Coelho", reason: "Spiritual journey" },
      { title: "Essays by Montaigne", reason: "Reflective and wise" },
    ],
    activities: [
      { title: "Meditate for 10 minutes", reason: "Clear your mind" },
      { title: "Go for a slow walk", reason: "Mindful movement" },
      { title: "Read poetry", reason: "Beautiful language" },
      { title: "Draw or paint", reason: "Peaceful creation" },
      { title: "Sit by water", reason: "Soothing nature" },
      { title: "Practice tea ceremony", reason: "Mindful ritual" },
      { title: "Garden or plant care", reason: "Grounding activity" },
      { title: "Watch clouds or sunset", reason: "Pure observation" },
    ],
  },

  Excited: {
    movies: [
      { title: "Top Gun: Maverick", reason: "Adrenaline-pumping action" },
      { title: "Mad Max: Fury Road", reason: "Non-stop energy" },
      { title: "The Greatest Showman", reason: "Spectacle and celebration" },
      { title: "Avengers: Endgame", reason: "Epic and thrilling" },
      { title: "Mission: Impossible - Fallout", reason: "High-octane fun" },
      { title: "Baby Driver", reason: "Music and action combined" },
      { title: "Jumanji: Welcome to the Jungle", reason: "Adventure and humor" },
      { title: "The Lego Movie", reason: "Explosive creativity" },
    ],
    music: [
      { title: "Uptown Funk - Mark Ronson ft. Bruno Mars", reason: "Infectious energy" },
      { title: "Shut Up and Dance - Walk the Moon", reason: "Pure adrenaline" },
      { title: "Mr. Brightside - The Killers", reason: "Euphoric anthem" },
      { title: "Starboy - The Weeknd", reason: "Victory vibes" },
      { title: "Pump It Up - Elvis Costello", reason: "Driving rhythm" },
      { title: "Feel It Still - Portugal. The Man", reason: "Joyful chaos" },
      { title: "Don't You (Forget About Me) - Simple Minds", reason: "Iconic energy" },
      { title: "Walking on Sunshine", reason: "Boundless joy" },
    ],
    books: [
      { title: "Shoe Dog - Phil Knight", reason: "Inspiring entrepreneurship" },
      { title: "The Autobiography of Malcolm X", reason: "Powerful transformation" },
      { title: "Grit - Angela Duckworth", reason: "Motivational excellence" },
      { title: "Elon Musk Biography", reason: "Ambitious innovation" },
      { title: "Atomic Habits - James Clear", reason: "Exciting progress" },
      { title: "Lean In - Sheryl Sandberg", reason: "Empowering drive" },
      { title: "Good to Great - Jim Collins", reason: "Success stories" },
    ],
    activities: [
      { title: "Go for a run or workout", reason: "Channel energy physically" },
      { title: "Start a new project", reason: "Ride the excitement" },
      { title: "Plan something fun", reason: "Capitalize on mood" },
      { title: "Play sports", reason: "Competitive energy" },
      { title: "Call your friends", reason: "Share the excitement" },
      { title: "Travel or explore", reason: "Adventure awaits" },
      { title: "Learn something new", reason: "Expand your world" },
      { title: "Host a gathering", reason: "Spread the vibes" },
    ],
  },

  Focused: {
    movies: [
      { title: "The Social Network", reason: "Intense dialogue and ambition" },
      { title: "Whiplash", reason: "Obsessive excellence" },
      { title: "Steve Jobs", reason: "Perfectionism and vision" },
      { title: "The Prestige", reason: "Complex and thought-provoking" },
      { title: "Incendies", reason: "Deeply engaging" },
      { title: "Minari", reason: "Meditative and purposeful" },
      { title: "Drive", reason: "Minimal and focused" },
      { title: "2001: A Space Odyssey", reason: "Demanding contemplation" },
    ],
    music: [
      { title: "Focus Spotify Playlist", reason: "Curated concentration" },
      { title: "Lo-fi Hip Hop Mix", reason: "Non-distracting beats" },
      { title: "Deep Work - Various", reason: "Ambient focus" },
      { title: "Video Game Soundtracks", reason: "Designed for focus" },
      { title: "Tones and I Playlist", reason: "Energizing but not distracting" },
      { title: "Studio Ghibli Soundtracks", reason: "Inspiring background" },
      { title: "Hans Zimmer Scores", reason: "Driving motivation" },
      { title: "Inception Soundtrack", reason: "Intense focus mode" },
    ],
    books: [
      { title: "Deep Work - Cal Newport", reason: "Master focus" },
      { title: "Atomic Habits - James Clear", reason: "Build focus systems" },
      { title: "The War of Art - Steven Pressfield", reason: "Overcome resistance" },
      { title: "Peak Performance", reason: "Optimize your mind" },
      { title: "Flow - Mihaly Csikszentmihalyi", reason: "Understand focus state" },
      { title: "Getting Things Done - David Allen", reason: "Clear your mind" },
      { title: "The 4-Hour Workweek - Tim Ferriss", reason: "Work smart" },
    ],
    activities: [
      { title: "Work in a quiet space", reason: "Minimize distractions" },
      { title: "Use the Pomodoro Technique", reason: "Focused work sprints" },
      { title: "Turn off notifications", reason: "Protect your focus" },
      { title: "Do your hardest task first", reason: "Leverage peak focus" },
      { title: "Take a short walk", reason: "Reset and refocus" },
      { title: "Meditate for focus", reason: "Sharpen attention" },
      { title: "Cold shower", reason: "Activate alertness" },
      { title: "Set a clear goal", reason: "Direct your energy" },
    ],
  },

  Tired: {
    movies: [
      { title: "Spirited Away", reason: "Soothing escapism" },
      { title: "My Neighbor Totoro", reason: "Cozy comfort" },
      { title: "Ponyo", reason: "Gentle and magical" },
      { title: "The Secret of Kells", reason: "Visually soft" },
      { title: "A Quiet Place", reason: "Low energy film" },
      { title: "Aftersun", reason: "Quiet contemplation" },
      { title: "Past Lives", reason: "Meditative and gentle" },
      { title: "The Terminal", reason: "Charming and low-stress" },
    ],
    music: [
      { title: "Sleep Soundtracks", reason: "Drift away" },
      { title: "Ambient Sleep Music", reason: "Restful tones" },
      { title: "Peaceful Piano", reason: "Calming melodies" },
      { title: "Bedtime Stories - Various", reason: "Soothing voices" },
      { title: "Rain and Thunder Sounds", reason: "Natural sleep aid" },
      { title: "Nick Drake", reason: "Soft and intimate" },
      { title: "Bon Iver - For Emma", reason: "Cozy bedroom vibes" },
      { title: "Birdy Discography", reason: "Gentle vocals" },
    ],
    books: [
      { title: "The House in the Cerulean Sea", reason: "Cozy and sweet" },
      { title: "Winnie the Pooh", reason: "Wholesome and simple" },
      { title: "A Wizard of Earthsea", reason: "Gentle adventure" },
      { title: "The Blue Cottage Book Series", reason: "Comfort reading" },
      { title: "Light contemporary romance", reason: "Easy reads" },
      { title: "Short story collections", reason: "Bite-sized tales" },
      { title: "Poetry anthologies", reason: "Beautiful brevity" },
    ],
    activities: [
      { title: "Take a nap", reason: "Recharge your energy" },
      { title: "Have warm tea", reason: "Soothing ritual" },
      { title: "Take a relaxing bath", reason: "Ease your body" },
      { title: "Stretch gently", reason: "Release tension" },
      { title: "Read for 15 minutes", reason: "Ease into rest" },
      { title: "Organize something small", reason: "Low-energy task" },
      { title: "Listen to a podcast", reason: "Passive entertainment" },
      { title: "Go to bed early", reason: "Honor your body's need" },
    ],
  },

  Angry: {
    movies: [
      { title: "Fight Club", reason: "Cathartic intensity" },
      { title: "Requiem for a Dream", reason: "Powerful emotions" },
      { title: "Nightcrawler", reason: "Dark and intense" },
      { title: "Goodfellas", reason: "Raw energy" },
      { title: "The Wolf of Wall Street", reason: "Chaotic energy" },
      { title: "American Psycho", reason: "Darkly engaging" },
      { title: "Uncut Gems", reason: "Frenetic tension" },
      { title: "Parasite", reason: "Righteous fury" },
    ],
    music: [
      { title: "Rage Against the Machine", reason: "Cathartic anger" },
      { title: "Eminem - Lose Yourself", reason: "Aggressive energy" },
      { title: "Slayer", reason: "Raw intensity" },
      { title: "Linkin Park - In the End", reason: "Angry release" },
      { title: "Deftones", reason: "Heavy catharsis" },
      { title: "System of a Down", reason: "Powerful statements" },
      { title: "Metallica - Enter Sandman", reason: "Power and control" },
      { title: "Pantera", reason: "Raw metal fury" },
    ],
    books: [
      { title: "Educated - Tara Westover", reason: "Empowering story" },
      { title: "The New Jim Crow - Michelle Alexander", reason: "Righteous anger" },
      { title: "Lean In - Sheryl Sandberg", reason: "Assert yourself" },
      { title: "Bad Blood - John Carreyrou", reason: "Justice revealed" },
      { title: "The Hate U Give", reason: "Powerful activism" },
      { title: "Educated - Complex emotions", reason: "Cathartic truth" },
      { title: "Non-fiction about injustice", reason: "Channel energy toward change" },
    ],
    activities: [
      { title: "Go to the gym hard", reason: "Physical release" },
      { title: "Go for an aggressive run", reason: "Burn off energy" },
      { title: "Hit a punching bag", reason: "Safe aggression outlet" },
      { title: "Scream into a pillow", reason: "Release frustration" },
      { title: "Write angry letters (don't send)", reason: "Get it out" },
      { title: "Do intense workout", reason: "Channel rage productively" },
      { title: "Organize/rearrange space", reason: "Control and power" },
      { title: "Join a cause", reason: "Direct anger toward change" },
    ],
  },

  Loved: {
    movies: [
      { title: "About Time", reason: "Beautiful family love" },
      { title: "Coco", reason: "Love beyond life" },
      { title: "The Farewell", reason: "Family bonds" },
      { title: "Life is Beautiful", reason: "Unconditional love" },
      { title: "Amélie", reason: "Spreading love" },
      { title: "When Harry Met Sally", reason: "Deep connection" },
      { title: "Crazy Rich Asians", reason: "Family and fashion" },
      { title: "The Grand Budapest Hotel", reason: "Whimsical affection" },
    ],
    music: [
      { title: "Make You Feel My Love - Adele", reason: "Pure devotion" },
      { title: "All of Me - John Legend", reason: "Unconditional" },
      { title: "Perfect - Ed Sheeran", reason: "Romantic bliss" },
      { title: "I Will Follow You Into the Dark - Death Cab for Cutie", reason: "Deep love" },
      { title: "At Last - Etta James", reason: "Timeless romance" },
      { title: "Three Times a Lady - Commodores", reason: "Sweet affection" },
      { title: "Lover - Taylor Swift", reason: "Joyful devotion" },
      { title: "Lucky - Jason Mraz", reason: "Grateful love" },
    ],
    books: [
      { title: "The Time Traveler's Wife", reason: "Epic love story" },
      { title: "Red, White & Royal Blue", reason: "Fun romance" },
      { title: "Outlander - Diana Gabaldon", reason: "Passionate love" },
      { title: "The Love Hypothesis", reason: "Heartwarming romance" },
      { title: "People We Meet on Vacation", reason: "Sweet chemistry" },
      { title: "It Ends With Us", reason: "Complex love" },
      { title: "The Hating Game", reason: "Fun romantic tension" },
    ],
    activities: [
      { title: "Call someone you love", reason: "Share the feeling" },
      { title: "Write a love letter", reason: "Express your feelings" },
      { title: "Cook a special meal", reason: "Show love through food" },
      { title: "Spend quality time", reason: "Deepen connection" },
      { title: "Give a sincere compliment", reason: "Spread the love" },
      { title: "Plan a surprise", reason: "Show you care" },
      { title: "Hug someone tight", reason: "Physical affection" },
      { title: "Journal gratitude", reason: "Appreciate those you love" },
    ],
  },

  Confident: {
    movies: [
      { title: "Rocky", reason: "Underdog triumph" },
      { title: "Legally Blonde", reason: "Self-assured excellence" },
      { title: "Hidden Figures", reason: "Inspiring brilliance" },
      { title: "The Pursuit of Happyness", reason: "Determined success" },
      { title: "Erin Brockovich", reason: "Unstoppable woman" },
      { title: "Gladiator", reason: "Powerful presence" },
      { title: "Wonder Woman", reason: "Strength and grace" },
      { title: "Glow Up: The Story", reason: "Self-transformation" },
    ],
    music: [
      { title: "Survivor - Destiny's Child", reason: "Empowering anthem" },
      { title: "Run the World (Girls) - Beyoncé", reason: "Pure confidence" },
      { title: "Roar - Katy Perry", reason: "Powerful energy" },
      { title: "Don't Stop Believin' - Journey", reason: "Iconic confidence" },
      { title: "Eye of the Tiger - Survivor", reason: "Unstoppable" },
      { title: "Queen - Various", reason: "Royal vibes" },
      { title: "Lizzo - Truth Hurts", reason: "Self-love anthem" },
      { title: "Shut Up and Dance - Walk the Moon", reason: "Carefree power" },
    ],
    books: [
      { title: "Lean In - Sheryl Sandberg", reason: "Assert your power" },
      { title: "Daring Greatly - Brené Brown", reason: "Confident vulnerability" },
      { title: "The Girl With the Dragon Tattoo", reason: "Fierce protagonist" },
      { title: "Educated - Tara Westover", reason: "Self-made strength" },
      { title: "Shoe Dog - Phil Knight", reason: "Confident vision" },
      { title: "Becoming - Michelle Obama", reason: "Inspiring journey" },
      { title: "The Confidence Code", reason: "Build your power" },
    ],
    activities: [
      { title: "Wear something that makes you feel powerful", reason: "External confidence" },
      { title: "Practice power poses", reason: "Physiology shifts psychology" },
      { title: "Do something you're good at", reason: "Reinforce confidence" },
      { title: "Take a cold shower", reason: "Mental toughness" },
      { title: "Compliment yourself", reason: "Own your excellence" },
      { title: "Public speaking practice", reason: "Build courage" },
      { title: "Try something new", reason: "Expand your boundaries" },
      { title: "Share your achievements", reason: "Celebrate yourself" },
    ],
  },

  Thoughtful: {
    movies: [
      { title: "Arrival", reason: "Intellectually profound" },
      { title: "Mulholland Drive", reason: "Enigmatic and deep" },
      { title: "Memento", reason: "Mind-bending complexity" },
      { title: "Tree of Life", reason: "Existential beauty" },
      { title: "Under the Skin", reason: "Philosophical sci-fi" },
      { title: "A Ghost Story", reason: "Contemplative mortality" },
      { title: "Synecdoche, New York", reason: "Complex narrative" },
      { title: "Stalker", reason: "Deep philosophical inquiry" },
    ],
    music: [
      { title: "Radiohead - OK Computer", reason: "Introspective genius" },
      { title: "Phoebe Bridgers - Punisher", reason: "Thoughtful introspection" },
      { title: "Bon Iver - 22, A Million", reason: "Complex emotions" },
      { title: "Kendrick Lamar - good kid, m.A.A.d city", reason: "Layered storytelling" },
      { title: "Arcade Fire", reason: "Existential themes" },
      { title: "The National", reason: "Contemplative indie" },
      { title: "Sigur Rós", reason: "Thoughtful atmosphere" },
      { title: "Pixies", reason: "Alternative depth" },
    ],
    books: [
      { title: "The Brothers Karamazov", reason: "Deep philosophy" },
      { title: "Beloved - Toni Morrison", reason: "Profound literature" },
      { title: "The Unbearable Lightness of Being", reason: "Existential classic" },
      { title: "Crime and Punishment", reason: "Moral complexity" },
      { title: "Norwegian Wood - Murakami", reason: "Meditative prose" },
      { title: "The Glass Menagerie", reason: "Lyrical introspection" },
      { title: "Essays by David Foster Wallace", reason: "Brilliant analysis" },
    ],
    activities: [
      { title: "Take a contemplative walk", reason: "Let ideas flow" },
      { title: "Write in a journal", reason: "Explore your thoughts" },
      { title: "Have a deep conversation", reason: "Exchange ideas" },
      { title: "Visit a museum", reason: "Contemplate art" },
      { title: "Read philosophy", reason: "Challenge your mind" },
      { title: "Sit with your thoughts", reason: "Embrace stillness" },
      { title: "Watch a documentary", reason: "Expand understanding" },
      { title: "Meditate on a question", reason: "Seek inner wisdom" },
    ],
  },
};

// Generate recommendations based on mood and intensity
export function generateRecommendations(mood, intensity) {
  const moodData = recommendationDatabase[mood.label];
  if (!moodData) return null;

  const shuffle = (array) => {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
  };

  // Add variation based on intensity
  const getRandomSubset = (array, count) => {
    return shuffle(array).slice(0, count);
  };

  const itemCount = intensity === "Mild" ? 2 : intensity === "Moderate" ? 3 : 4;

  return {
    movies: getRandomSubset(moodData.movies, itemCount),
    music: getRandomSubset(moodData.music, itemCount),
    books: getRandomSubset(moodData.books, itemCount),
    activities: getRandomSubset(moodData.activities, itemCount),
  };
}
